### ISSUE TITLE
prepare_climate() currently single use

### ISSUE THREAD

**Issue by moritzshore** [biopsichas/SWATprepR#1]
> Hi, first off, love the package, makes so much stuff so much easier. Thanks for making it.

 The `prepare_climate()` function works for me when I use it on a fresh setup, however running it again on the same setup leads to this error:

![image](https://github.com/biopsichas/SWATprepR/assets/99182918/ab9a02df-f629-4b99-ad66-a8c1842a7046)

You can replicate this error (probably) with your own setup (https://github.com/biopsichas/Zglowiaczka), however its possible its due to my input data as well. Let me know if you can't replicate and I'll send you my input data. 

A fix would be nice great! 👍 I'm using it within my own "tools" package which will take download gridded reanalysis data and pipe it into SWAT+ input, with much assistance from your package.

**Comment by biopsichas** [comment]
Hi Moritz,

Thanks being a user and reporting a bug :) Glad to hear it makes things
easier. Yep, I reproduced this error with my setup. And now updated the
package. So it should be working for you.

Best wishes,
Svajunas
