### ISSUE TITLE
`location` parameter error with load_netcdf_weather and location "list"

### ISSUE THREAD

**Issue by echiaradia** [biopsichas/SWATprepR#2]
I load the weather stations data from template xlsx file. The data are loaded as list but list isn't accepted by the load_netcdf_weather function. It seems an error in the IF block at line 551 of loading.R file.

**Comment by echiaradia** [comment]
Please check my edits if they make sense for you:
https://github.com/echiaradia/SWATprepR/commit/1be99b44495949ef829f16b9663def3d5fb07f4d

**Comment by biopsichas** [comment]
Hi Enrico, thanks for providing feedback on this function and corrections in the code. I was in the end of debugging in the moment of receiving your code, so left my version. But anyway I updated function to remove those bugs. You can use my version if you update the package ;)
