### ISSUE TITLE
A way to update the TxtInOut files without updating the SQL database?

### ISSUE THREAD

**Issue by moritzshore** [biopsichas/SWATprepR#6]
Hey, 

I know we at OPTAIN/CS10 use our Database+TxtInOut a little differently than you do (ie. after running `buildR` we don't modify the SQL anymore, just edit the text files it gave us). But for this reason most of the `prepR` functions only **half** work for us. Such as `add_atmo_dep`. It does work as it writes our text file which we want, but then the function gets an error trying to write to an SQL which we don't use (or need). An easy way for us to get around this is to just run the function, let it write our text file, and then catch the error. 

An example is below: where the db_path does not contain an SQL. It works as atmodep.cli is wrriten out, however the error must be caught. 

```
hacked_atmodep <- function(df, db_path, t_ext) {
+     tryCatch(
+         {
+             SWATprepR::add_atmo_dep(df,db_path, t_ext)
+         },
+         error = function(e) {
+             message('catching the error')
+             print(e)
+         }
+     )
+ }

> 
> hacked_atmodep(df, "model_data/cs10_setup/scenarios/baseline/", "annual")
[1] "Atmospheric deposition data were written into  model_data/cs10_setup/scenarios/baseline/atmodep.cli"
catching the error: : Could not connect to database: unable to open database file
```

So a suggestion I would like to make is to just add an extra flag of whether or not to update the SQL. **I could implement it myself and add a pull request if you would like?**

**Comment by biopsichas** [comment]
Hi Moritz, very good suggestion. I put this on a list to fix this sometime, but you are very welcome to update this function.
